# Generated by Django 2.2.6 on 2020-08-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200813_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_referred',
            field=models.BooleanField(default=False),
        ),
    ]
