# Generated by Django 2.2.6 on 2020-08-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_profile_is_referred'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_referred',
            field=models.BooleanField(default=False),
        ),
    ]
