# Generated by Django 2.2.6 on 2020-08-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_auto_20200817_1207"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile", name="slug", field=models.SlugField(blank=True),
        ),
    ]
