# Generated by Django 2.2.6 on 2020-09-16 09:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_profile_avatar_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_thumbnail',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
