# Generated by Django 2.2.6 on 2019-12-17 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField()),
                ('url', models.URLField()),
                ('rank', models.CharField(choices=[('1', 'Kami'), ('2', 'S'), ('3', 'A'), ('4', 'B'), ('5', 'Unranked')], default=('5', 'Unranked'), max_length=32)),
                ('slug', models.SlugField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MangaTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserManga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read', models.DateTimeField(blank=True)),
                ('chapter', models.IntegerField(blank=True)),
                ('page', models.IntegerField(blank=True)),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Manga')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='manga',
            name='tags',
            field=models.ManyToManyField(blank=True, to='backend.MangaTag'),
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mangas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.UserManga')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
