# Generated by Django 2.2.6 on 2020-03-06 08:59

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.FloatField()),
                ('date_uploaded', models.DateTimeField()),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('pages', django.contrib.postgres.fields.jsonb.JSONField()),
                ('manga_alias', models.CharField(blank=True, max_length=100, null=True)),
                ('chapter_type', models.CharField(choices=[('0', 'MANGAEDEN'), ('1', 'MANGANELO')], max_length=50)),
            ],
            options={
                'ordering': ['date_uploaded'],
            },
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manga_type', models.CharField(choices=[('0', 'MANGANELO')], max_length=32)),
                ('chapters_length', models.IntegerField(default=0)),
                ('author', models.CharField(max_length=70)),
                ('last_updated', models.DateTimeField()),
                ('title', models.TextField(max_length=200)),
                ('description', models.TextField()),
                ('hits', models.IntegerField()),
                ('other_names', models.TextField(blank=True)),
                ('alias', models.TextField(max_length=50, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('0', 'Finished'), ('1', 'Ongoing')], max_length=32)),
                ('image_url', models.URLField()),
                ('rank', models.CharField(choices=[('1', 'Kami'), ('2', 'S'), ('3', 'A'), ('4', 'B'), ('5', 'Unranked')], default=('5', 'Unranked'), max_length=32)),
                ('baka', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, default='', max_length=200, null=True)),
                ('tags_string', models.TextField()),
                ('thoughts', models.TextField(blank=True, null=True)),
                ('rank_reason', models.TextField(blank=True, null=True)),
                ('publisher_url', models.URLField(blank=True, null=True)),
                ('publisher_url_2', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['last_updated'],
            },
        ),
        migrations.CreateModel(
            name='MangaTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=48)),
                ('clicks', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserManga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read', models.DateTimeField(auto_now_add=True)),
                ('alias', models.CharField(max_length=70)),
                ('isfavorite', models.BooleanField(default=False)),
                ('anonymous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sessions.Session')),
                ('chapters', models.ManyToManyField(to='backend.Chapter')),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Manga')),
                ('new_chapters', models.ManyToManyField(related_name='recent_chapters', to='backend.Chapter')),
            ],
        ),
    ]
