# Generated by Django 2.2.6 on 2020-04-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('content', models.TextField()),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapters_length', models.IntegerField(default=0)),
                ('author', models.CharField(max_length=70)),
                ('last_updated', models.DateTimeField()),
                ('title', models.TextField(max_length=200)),
                ('description', models.TextField()),
                ('hits', models.IntegerField()),
                ('other_names', models.TextField(blank=True)),
                ('alias', models.TextField(max_length=50, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('0', 'Finished'), ('1', 'Ongoing')], max_length=32)),
                ('image_url', models.URLField()),
                ('rank', models.CharField(choices=[('1', 'Kami'), ('2', 'S'), ('3', 'A'), ('4', 'B'), ('5', 'Unranked')], default='5', max_length=32)),
                ('baka', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, default='', max_length=200, null=True)),
                ('tags_string', models.TextField()),
                ('thoughts', models.TextField(blank=True, null=True)),
                ('rank_reason', models.TextField(blank=True, null=True)),
                ('publisher_url', models.URLField(blank=True, null=True)),
                ('publisher_url_2', models.URLField(blank=True, null=True)),
                ('scanlator_1', models.URLField(blank=True, null=True)),
                ('scanlator_2', models.URLField(blank=True, null=True)),
                ('media_type', models.CharField(choices=[('0', 'Manga'), ('1', 'Anime')], max_length=32)),
            ],
            options={
                'ordering': ['-hits'],
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=48)),
                ('clicks', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ReviewVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('1', 'Like'), ('2', 'Dislike')], max_length=32)),
            ],
        ),
    ]
