# Generated by Django 2.2.6 on 2019-12-17 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Manga')),
            ],
        ),
        migrations.RemoveField(
            model_name='usermanga',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='usermanga',
            name='page',
        ),
        migrations.CreateModel(
            name='UserChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=False)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Chapter')),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.UserManga')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
