# Generated by Django 2.2.6 on 2020-03-06 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backend', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usermanga',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='manga',
            name='publisher',
            field=models.ManyToManyField(blank=True, to='backend.Publisher'),
        ),
        migrations.AddField(
            model_name='manga',
            name='tags',
            field=models.ManyToManyField(blank=True, to='backend.MangaTag'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='manga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='backend.Manga'),
        ),
    ]
