# Generated by Django 2.2.6 on 2020-04-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20200416_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='alias',
            field=models.TextField(max_length=50),
        ),
    ]
