# Generated by Django 2.2.6 on 2020-04-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20200416_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='media-images'),
        ),
    ]
