# Generated by Django 2.2.6 on 2020-04-16 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20200416_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='weekly_reads',
            field=models.IntegerField(default=0),
        ),
    ]
