# Generated by Django 2.2.6 on 2020-04-17 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20200417_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='image_url',
            field=models.URLField(),
        ),
    ]
