# Generated by Django 2.2.6 on 2020-04-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20200417_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
