# Generated by Django 2.2.6 on 2020-04-21 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20200421_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='elitemanga_review',
        ),
        migrations.AddField(
            model_name='elitemangareview',
            name='media_review',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Media'),
        ),
    ]
