# Generated by Django 2.2.6 on 2020-04-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20200421_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elitemangareview',
            name='characters',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='elitemangareview',
            name='originality',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='elitemangareview',
            name='plot',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='elitemangareview',
            name='quality',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='elitemangareview',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='elitemangareview',
            name='total_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
