# Generated by Django 2.2.6 on 2020-04-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20200421_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='unreleased',
        ),
        migrations.AlterField(
            model_name='media',
            name='status',
            field=models.CharField(choices=[('0', 'Finished'), ('1', 'Ongoing'), ('2', 'Unreleased')], max_length=32),
        ),
    ]
