# Generated by Django 2.2.6 on 2020-05-02 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_list_listsection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listsection',
            old_name='rank',
            new_name='position',
        ),
    ]
