# Generated by Django 2.2.6 on 2020-05-02 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_auto_20200502_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='image',
            field=models.ImageField(default='shift', upload_to='list-images'),
            preserve_default=False,
        ),
    ]
