# Generated by Django 2.2.6 on 2020-05-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_list_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='characters_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='originality_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='plot_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='quality_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='total_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
