# Generated by Django 2.2.6 on 2020-06-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_remove_review_total_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='list-images'),
        ),
    ]
