# Generated by Django 2.2.6 on 2020-06-08 19:03

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('backend', '0023_auto_20200603_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
