# Generated by Django 2.2.6 on 2020-06-10 11:42

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('backend', '0024_list_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaggedList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='list',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='backend.TaggedList', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='taggedlist',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.List'),
        ),
        migrations.AddField(
            model_name='taggedlist',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backend_taggedlist_items', to='taggit.Tag'),
        ),
    ]
