# Generated by Django 2.2.6 on 2020-06-10 12:56

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_auto_20200610_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCustomTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'ListTag',
                'verbose_name_plural': 'ListTags',
            },
        ),
        migrations.AlterField(
            model_name='list',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='backend.TaggedList', to='backend.MyCustomTag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='taggedlist',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backend_taggedlist_items', to='backend.MyCustomTag'),
        ),
    ]
