# Generated by Django 2.2.6 on 2020-06-10 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_auto_20200610_1356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mycustomtag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
    ]
