# Generated by Django 2.2.6 on 2020-06-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_auto_20200610_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='status',
            field=models.CharField(choices=[('0', 'Finished'), ('1', 'Ongoing'), ('2', 'Unreleased'), ('3', 'Upcoming')], max_length=32),
        ),
    ]
