# Generated by Django 2.2.6 on 2020-06-17 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_auto_20200615_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='media-images'),
        ),
    ]
