# Generated by Django 2.2.6 on 2020-06-29 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_auto_20200629_1010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='link',
            new_name='homepage',
        ),
        migrations.RemoveField(
            model_name='media',
            name='source',
        ),
        migrations.AddField(
            model_name='source',
            name='type',
            field=models.CharField(choices=[('1', 'Webtoons'), ('2', 'Crunchyroll'), ('3', 'Mangakakalot'), ('4', 'anime-planet'), ('5', 'Animepahe'), ('6', 'Netflix'), ('7', 'Toomics')], default='1', max_length=40),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SourceLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Media')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Source')),
            ],
        ),
        migrations.AddField(
            model_name='media',
            name='sources',
            field=models.ManyToManyField(blank=True, null=True, through='backend.SourceLink', to='backend.Source'),
        ),
    ]
