# Generated by Django 2.2.6 on 2020-06-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0032_auto_20200629_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='official',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='media',
            name='sources',
            field=models.ManyToManyField(blank=True, through='backend.SourceLink', to='backend.Source'),
        ),
    ]
