# Generated by Django 2.2.6 on 2020-06-30 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0034_remove_source_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='rating',
        ),
        migrations.AlterField(
            model_name='source',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
