# Generated by Django 2.2.6 on 2020-07-31 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0036_announcement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='uploaded_on',
            new_name='date_written',
        ),
    ]
