# Generated by Django 2.2.6 on 2020-07-31 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0038_announcement_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='slug',
        ),
    ]
