# Generated by Django 2.2.6 on 2020-07-31 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0041_auto_20200731_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='slug',
        ),
    ]
