# Generated by Django 2.2.6 on 2020-08-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0044_campaign_referral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referrals',
            field=models.ManyToManyField(blank=True, related_name='referred', related_query_name='referred', to='users.Profile'),
        ),
    ]
