# Generated by Django 2.2.6 on 2020-08-20 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0046_campaign_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elitemangareview',
            old_name='originality_score',
            new_name='moment_score',
        ),
    ]
