# Generated by Django 2.2.6 on 2020-08-20 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0047_auto_20200820_1101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elitemangareview',
            old_name='originality',
            new_name='moment',
        ),
    ]
