# Generated by Django 2.2.6 on 2020-08-20 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0048_auto_20200820_1105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='originality_score',
            new_name='moment_score',
        ),
    ]
