# Generated by Django 2.2.6 on 2020-08-22 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0049_auto_20200820_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='adaptation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Media'),
        ),
    ]
