# Generated by Django 2.2.6 on 2020-08-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0050_media_adaptation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elitemangareview',
            name='characters',
            field=models.TextField(blank=True, default='<p><b>Personality:</b></p><p><b>Chemistry:</b></p><p><b>Backdrop:</b></p><p><b>Likability:</b></p><p><b>Development:</b></p>', null=True),
        ),
        migrations.AlterField(
            model_name='elitemangareview',
            name='moment',
            field=models.TextField(blank=True, default='<p><b>Presentation:</b></p><p><b>Consistency:</b></p><p><b>Predictability:</b></p><p><b>Effort:</b></p><p><b>Main Genre of Moments:</b></p><p><b><br></b></p>', null=True),
        ),
        migrations.AlterField(
            model_name='elitemangareview',
            name='plot',
            field=models.TextField(blank=True, default='<p><span style="font-weight: 700;">Realism:</span></p><p><span style="font-weight: 700;">Premise:</span></p><p><span style="font-weight: 700;">Pacing:</span></p><p><span style="font-weight: 700;">Complexity:</span></p><p><span style="font-weight: 700;">Immersion:</span></p><p><span style="font-weight: 700;">Conclusion:</span></p>', null=True),
        ),
        migrations.AlterField(
            model_name='elitemangareview',
            name='quality',
            field=models.TextField(blank=True, default='<p><b>Sound:</b></p><p><b>Voice Acting:</b></p><p><b>Art style:</b></p><p><b>Animation Quality:</b></p>', null=True),
        ),
    ]
