# Generated by Django 2.2.6 on 2020-09-05 21:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0053_listsection_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='list-images/p.png', max_length=255, null=True),
        ),
    ]
