# Generated by Django 2.2.6 on 2020-09-15 08:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0058_auto_20200913_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='image_url',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
